<?php

namespace Database\Seeders;

use App\Models\Testimonial;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TestimonialSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $testimonials = [
            // website-development (4)
            [
                'client_name'    => 'Amit Patel',
                'client_title'   => 'Founder',
                'client_company' => 'Aroma Monk',
                'content'        => 'Our wholesale inquiries tripled in the first three months after the new website launched. The dual B2B/B2C structure was exactly what we needed — retail customers get a clean shopping experience while distributors get trade pricing without any confusion.',
                'rating'         => 5,
                'service_tags'   => ['website-development'],
                'industry_tags'  => ['retail'],
                'solution_slug'  => null,
                'is_featured'    => true,
                'is_published'   => true,
                'sort_order'     => 1,
            ],
            [
                'client_name'    => 'Vikram Singh',
                'client_title'   => 'Sales Director',
                'client_company' => 'SRJ Industries',
                'content'        => 'International buyers now find us before our competitors — that didn\'t happen before. The product catalogue with spec sheet downloads has shortened our sales cycle because buyers come in already knowing what they want. We went from 4 export inquiries a month to over 20.',
                'rating'         => 5,
                'service_tags'   => ['website-development'],
                'industry_tags'  => ['manufacturing'],
                'solution_slug'  => null,
                'is_featured'    => true,
                'is_published'   => true,
                'sort_order'     => 2,
            ],
            [
                'client_name'    => 'Sanjay Gupta',
                'client_title'   => 'Export Manager',
                'client_company' => 'GNC Exports',
                'content'        => 'The website Buildera built positioned us exactly the way we needed in global markets. Our ISO certifications and facility photos are front and centre, which was the first thing European buyers asked to see. We signed our first European distribution agreement within 5 months.',
                'rating'         => 5,
                'service_tags'   => ['website-development'],
                'industry_tags'  => ['manufacturing'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 3,
            ],
            [
                'client_name'    => 'Meera Nair',
                'client_title'   => 'Founder',
                'client_company' => 'Bloom & Brew Co.',
                'content'        => 'We went from zero online presence to a fully functional e-commerce store in 6 weeks. The checkout is fast, the product photography layout looks premium, and we\'re now consistently converting Instagram traffic into paying customers. Best investment we made this year.',
                'rating'         => 5,
                'service_tags'   => ['website-development'],
                'industry_tags'  => ['retail'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 4,
            ],

            // salesforce-development (3)
            [
                'client_name'    => 'Rohit Mehta',
                'client_title'   => 'VP of Sales',
                'client_company' => 'Nexgen Infra Solutions',
                'content'        => 'Our Salesforce implementation was a mess before Buildera stepped in — data in three objects that didn\'t talk to each other, no meaningful reports, and a sales team that had given up using the CRM. They rebuilt our data architecture and automated our proposal workflow. Our forecast accuracy went from embarrassing to something we can actually present to the board.',
                'rating'         => 5,
                'service_tags'   => ['salesforce-development'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => 'sales-mgmt',
                'is_featured'    => true,
                'is_published'   => true,
                'sort_order'     => 5,
            ],
            [
                'client_name'    => 'Kavitha Reddy',
                'client_title'   => 'Operations Head',
                'client_company' => 'BrightPath Consulting',
                'content'        => 'The custom Salesforce flows they built replaced 6 hours of manual weekly admin. Our client onboarding process — contracts, task creation, team assignment — now triggers automatically when a deal closes. The team actually uses Salesforce now, which says everything.',
                'rating'         => 4,
                'service_tags'   => ['salesforce-development'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => 'crm',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 6,
            ],
            [
                'client_name'    => 'Deepak Sharma',
                'client_title'   => 'Managing Director',
                'client_company' => 'Optima Financial Services',
                'content'        => 'We needed Salesforce to handle our NBFC-specific compliance workflows and Buildera delivered without needing us to explain financial services twice. Lead deduplication, KYC status tracking, and loan stage automation all work exactly as designed. Implementation was on time and the training was thorough.',
                'rating'         => 5,
                'service_tags'   => ['salesforce-development'],
                'industry_tags'  => ['finance'],
                'solution_slug'  => 'lead-mgmt',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 7,
            ],

            // devops-development (3)
            [
                'client_name'    => 'Arjun Krishnamurthy',
                'client_title'   => 'CTO',
                'client_company' => 'Stacklytics',
                'content'        => 'We were deploying manually over SSH like it was 2012. Buildera set up our entire CI/CD pipeline on GitHub Actions with automated testing, staging deployments, and blue-green production releases. Our deployment confidence went from dreading Fridays to shipping whenever we\'re ready.',
                'rating'         => 5,
                'service_tags'   => ['devops-development'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 8,
            ],
            [
                'client_name'    => 'Nisha Pillai',
                'client_title'   => 'Engineering Manager',
                'client_company' => 'Ventura Logistics Tech',
                'content'        => 'Our AWS costs were out of control and our infrastructure was undocumented. Buildera audited, right-sized our instances, implemented auto-scaling, and handed us Terraform configs for everything. Infra costs down 38% — that paid for the engagement in 90 days.',
                'rating'         => 5,
                'service_tags'   => ['devops-development'],
                'industry_tags'  => ['logistics'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 9,
            ],
            [
                'client_name'    => 'Ravi Sundaram',
                'client_title'   => 'Founder',
                'client_company' => 'DocuFlow AI',
                'content'        => 'They containerised our entire application stack with Docker, set up Kubernetes on AWS EKS, and configured monitoring with Prometheus and Grafana. What used to take 3 hours to deploy now takes 8 minutes. The observability they set up means we find issues before our users do.',
                'rating'         => 5,
                'service_tags'   => ['devops-development'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 10,
            ],

            // ai-agent-development (3)
            [
                'client_name'    => 'Suresh Iyer',
                'client_title'   => 'Head of Operations',
                'client_company' => 'PrimeTrade Wholesale',
                'content'        => 'Our IndiaMart leads were going cold by morning because nobody was responding at 11pm. Buildera built an AI agent that captures every enquiry, sends a WhatsApp response with our product catalogue within 60 seconds, and routes qualified leads to the right rep. Lead-to-conversation rate went from 22% to 71%.',
                'rating'         => 5,
                'service_tags'   => ['ai-agent-development'],
                'industry_tags'  => ['manufacturing'],
                'solution_slug'  => 'india-mart',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 11,
            ],
            [
                'client_name'    => 'Ananya Bose',
                'client_title'   => 'Customer Success Lead',
                'client_company' => 'ClarityDesk',
                'content'        => 'We were drowning in tier-1 support tickets that were the same 20 questions asked differently. The AI agent they built now handles 68% of support conversations without human escalation. Our support team is down to handling complex issues only — and response times for real problems have dropped dramatically.',
                'rating'         => 5,
                'service_tags'   => ['ai-agent-development'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 12,
            ],
            [
                'client_name'    => 'Manoj Tiwari',
                'client_title'   => 'Founder',
                'client_company' => 'AutoFin Solutions',
                'content'        => 'The n8n workflows Buildera set up automated our entire loan application intake — document collection, credit bureau pulls, underwriter assignment, and applicant communication. What was a 3-day manual process now completes in 4 hours. We processed 3x more applications last month with the same team size.',
                'rating'         => 5,
                'service_tags'   => ['ai-agent-development'],
                'industry_tags'  => ['finance'],
                'solution_slug'  => 'operations-mgmt',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 13,
            ],

            // software-development (4)
            [
                'client_name'    => 'Rajesh Kumar',
                'client_title'   => 'Operations Manager',
                'client_company' => 'Saharsh Packaging',
                'content'        => 'The ERP Buildera built gave us something we\'d never had — one version of the truth across sales, warehouse, and accounts. Month-end used to take four days of reconciliation. Now it\'s an 8-hour review. Stockouts are down 60% because we actually know what\'s in stock before we take the order.',
                'rating'         => 5,
                'service_tags'   => ['software-development'],
                'industry_tags'  => ['manufacturing'],
                'solution_slug'  => 'erp',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 14,
            ],
            [
                'client_name'    => 'Priya Sharma',
                'client_title'   => 'Hotel Manager',
                'client_company' => 'Ease My Hotel',
                'content'        => 'Buildera built the SaaS platform our hotel clients had been asking for. The multi-tenant architecture handles 18 properties seamlessly, and the OTA sync means our hotels haven\'t had a double-booking since launch. Check-in time is down from 12 minutes to under 2. The platform effectively sells itself.',
                'rating'         => 5,
                'service_tags'   => ['software-development'],
                'industry_tags'  => ['hospitality'],
                'solution_slug'  => 'hotels-resorts',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 15,
            ],
            [
                'client_name'    => 'Nikhil Reddy',
                'client_title'   => 'Owner',
                'client_company' => 'Barrel Books',
                'content'        => 'Managing stock across three liquor shops on paper registers was a nightmare. The Barrel Books platform they built does barcode intake, daily reconciliation, and excise register export automatically. End-of-day stock count went from 45 minutes to 8. We now run multi-location reports I genuinely couldn\'t have before.',
                'rating'         => 5,
                'service_tags'   => ['software-development'],
                'industry_tags'  => ['retail'],
                'solution_slug'  => 'warehouse-mgmt',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 16,
            ],
            [
                'client_name'    => 'Lakshmi Venkataraman',
                'client_title'   => 'Chief Financial Officer',
                'client_company' => 'Meridian Pharma',
                'content'        => 'The custom financial management system replaced our quarterly Excel consolidation exercise. Multi-entity financials now consolidate automatically in real time. Expense approvals that sat in inboxes for 4 days now complete in under 6 hours. Our CFO team has moved from data production to actual analysis.',
                'rating'         => 4,
                'service_tags'   => ['software-development'],
                'industry_tags'  => ['manufacturing'],
                'solution_slug'  => 'financial-mgmt',
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 17,
            ],

            // hire-a-developer (3)
            [
                'client_name'    => 'Karan Malhotra',
                'client_title'   => 'CTO',
                'client_company' => 'Growlytics',
                'content'        => 'We needed a senior Laravel developer to join our team permanently but didn\'t have 3 months to recruit. Buildera placed a developer who was productive from week one — and I mean genuinely productive, not ramping up. He\'s been with us 14 months now and has become a core part of the team.',
                'rating'         => 5,
                'service_tags'   => ['hire-a-developer'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 18,
            ],
            [
                'client_name'    => 'Tanvi Joshi',
                'client_title'   => 'Product Manager',
                'client_company' => 'HealthFirst Digital',
                'content'        => 'We hired two React developers on a 6-month retainer through Buildera for a product launch sprint. The flexible engagement meant we could scale down after the launch without awkward conversations about full-time contracts. Both developers were exactly the calibre described — senior, self-managing, and timezone-aligned.',
                'rating'         => 5,
                'service_tags'   => ['hire-a-developer'],
                'industry_tags'  => ['professional-services'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 19,
            ],
            [
                'client_name'    => 'Prakash Rao',
                'client_title'   => 'Founder',
                'client_company' => 'FreightLink Technologies',
                'content'        => 'After a failed agency engagement left us with a half-finished platform and no support, Buildera took over the codebase and provided end-to-end support covering maintenance, bug fixes, and new features. Having one team accountable for the full lifecycle — not three separate vendors — made all the difference. We\'ve had no critical outages in 18 months.',
                'rating'         => 5,
                'service_tags'   => ['hire-a-developer'],
                'industry_tags'  => ['logistics'],
                'solution_slug'  => null,
                'is_featured'    => false,
                'is_published'   => true,
                'sort_order'     => 20,
            ],
        ];

        foreach ($testimonials as $data) {
            Testimonial::updateOrCreate(
                ['client_name' => $data['client_name'], 'client_company' => $data['client_company']],
                $data
            );
        }
    }
}
