import { verifySession } from '@/backend/auth/session'
import { redirect } from 'next/navigation'

export default async function SitemapPage() {
  const session = await verifySession()
  if (!session) redirect('/admin/login')

  return (
    <div className="space-y-4 max-w-2xl">
      <h1 className="text-xl font-semibold text-gray-900">Sitemap</h1>
      <div className="bg-white rounded-xl border border-gray-200 p-6 space-y-4">
        <p className="text-sm text-gray-600">
          The sitemap is auto-generated by Next.js from <code className="bg-gray-100 px-1 rounded text-xs">src/app/sitemap.ts</code> at build time and revalidated when content is published.
        </p>
        <div className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
          <span className="text-sm text-gray-700 font-medium">Sitemap URL:</span>
          <a href="https://buildera.co/sitemap.xml" target="_blank" rel="noopener"
            className="text-sm text-primary hover:underline font-mono">
            https://buildera.co/sitemap.xml
          </a>
        </div>
        <p className="text-xs text-gray-400">
          To force-refresh after publishing new content, open the sitemap URL in a browser tab. Next.js ISR will regenerate it automatically within the revalidation window.
        </p>
      </div>
    </div>
  )
}
